#!/usr/bin/env python3

import blinky
import time as t

pins = [17,27,22,5,6,13,19,26]

try:
	while True:
		blinky.allon(17,27,22,5,6,13,19,26)
		t.sleep(.5)
		blinky.alloff(17,27,22,5,6,13,19,26)
		t.sleep(.5)

except KeyboardInterrupt:
	blinky.alloff(17,27,22,5,6,13,19,26)
	exit
