#!/usr/bin/env python3

import blinky
import time as t

try:
	while True:
		blinky.blinkdown(17,27,22,5,6,13,19,26)
		blinky.blinkup(17,27,22,5,6,13,19,26)

except KeyboardInterrupt:
	blinky.alloff(17,27,22,5,6,13,19,26)
	exit
	
